---
- name: Install and configure Magento 2 instances
  hosts: web
  any_errors_fatal: true
  vars_files:
    - ../../vars/magento2.yaml
  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - geerlingguy.nginx
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.composer
  tasks:
    - name: Remove anything that should not be here
      package:
        name: "{{ item }}"
        state: absent
      with_items:
        - httpd
    - name: Set the correct socket details
      lineinfile:
        dest: "{{ php_fpm_pool_conf_path }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - regexp: "^listen.owner.?=.+$"
          line: "listen.owner = {{ php_fpm_pool_user }}"
        - regexp: "^listen.group.?=.+$"
          line: "listen.group = {{ php_fpm_pool_group }}"
        - regexp: "^php_value\\[session.save_path\\].*"
          line: "php_value[session.save_path] = {{ magento2_base_dir }}/var/sessions"
      notify: restart php-fpm
