---
- name: Install and configure Magento 2 instances
  hosts: web
  any_errors_fatal: true
  vars_files:
    - ../../vars/magento2.yaml
  tasks:
    - name: Generate Host Keys
      command: ssh-keygen -A
      args:
        creates: /etc/ssh/ssh_host_key
    - name: Install pre-requisists
      package:
        name: "{{item}}"
        state: present
      with_items:
        - git
        - curl
        - vim
        - unzip
        - sudo
        - mysql
    - name: Create Base User
      user:
        name: "{{ magento2_fs_user }}"
        shell: /bin/bash
        generate_ssh_key: yes
