magento2_database_pass: >-
  "{{
  lookup('password',
  '{{ inventory_dir }}/one-time-passwords/magento2-mysql-password
  length=32
  chars=ascii_letters')
  }}"
magento2_rabbit_password: >-
  "{{
  lookup('password',
  '{{ inventory_dir }}/one-time-passwords/rabbit-password
  length=32
  chars=ascii_letters')
  }}"
magento2_admin_password: >-
  "{{
  lookup('password',
  '{{ inventory_dir }}/one-time-passwords/magento2-admin-password
  length=32
  chars=ascii_letters,digits')
  }}"
magento2_redis_password: >-
  "{{
  lookup('password',
  '{{ inventory_dir }}/one-time-passwords/redis-password
  length=32
  chars=ascii_letters,digits')
  }}"
